swagger: '2.0'
info:
  title: Nonprofit Search API
  description: Allows you to quickly search Nonprofit organizations
  version: "0.1.0"
# the domain of the service
host: nonprofit.app
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json
paths:
  /api/nonprofits/search:
    get:
      summary: Searching Nonprofits
      description: |
        Returns all the organizations of the given query string.  The function considers the name, ein, city and state of the organization.
      parameters:
        - name: q
          in: query
          description: The query search for the organization
          required: true
          type: string
      tags:
        - nonprofits
      responses:
        200:
          description: The results of the search
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/Nonprofit'

definitions:
  Nonprofit:
    type: object
    properties:
      id:
        type: integer
        description: the id of the nonprofit in the database.  Not critical as this might change when the data is refreshed
      ein:
        type: string
        description: the ein of the organization.  this is the value that's needed if query individually.
      name:
        type: string
        description: the name of the organization.
      city:
        type: string
        description: the city in which the organization resides.
      state:
        type: string
        description: the state in which the organization resides.
      deductibility_status_code:
        type: array
        description: the types of organization it is.  The value will always return an array, even if the organization is only one type of org.
        items:
          type: string